"""empty message

Revision ID: 4593bbcc343b
Revises: 87dcf7257cdf
Create Date: 2021-12-11 15:12:45.297395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4593bbcc343b'
down_revision = '87dcf7257cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charId', sa.String(length=120), nullable=True),
    sa.Column('planetId', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['charId'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['planetId'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
