"""empty message

Revision ID: 8d56c9eb1213
Revises: 15791a4b1d49
Create Date: 2021-12-11 13:00:33.660451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d56c9eb1213'
down_revision = '15791a4b1d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charName', sa.String(length=120), nullable=False),
    sa.Column('charBirthYear', sa.String(length=15), nullable=True),
    sa.Column('charGender', sa.String(length=15), nullable=True),
    sa.Column('charHairColor', sa.String(length=15), nullable=True),
    sa.Column('charEyeColor', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planetName', sa.String(length=120), nullable=False),
    sa.Column('planetClimate', sa.String(length=15), nullable=False),
    sa.Column('planetDiameter', sa.Integer(), nullable=False),
    sa.Column('planetPopulation', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    op.drop_table('characters')
    # ### end Alembic commands ###
